config/routes.rb
Spree::Core::Engine.add_routes do
  namespace :admin do
    resources :subscriptions, except: [:show, :destroy] do
      member do
        put :cancel
        put :renew
        put :skip
        put :undo_skip
        get :credit_card
        post :credit_card
      end
      collection do
        get :failures
        get :adjust_sku
        post :adjust_sku
      end
    end
  end

  namespace :api, defaults: { format: 'json' } do
    resources :subscriptions, except: [:create, :new, :destroy] do
      member do
        put :skip_next_order
        put :undo_skip_next_order
        put :pause
        put :resume
        post :create_address
        put :update_address
        put :select_address
        put :cancel
        post :create_credit_card
      end
      resources :subscription_items
    end
  end

  resources :subscriptions do
    member do
        put :pause
        put :resume
        put :cancel
        post :add_item
        get :credit_card
        post :credit_card
    end
    resources :subscription_items
  end
end

app/models/spree/subscription.rb
module Spree
  class Subscription < ActiveRecord::Base
    has_many :subscription_items, dependent: :destroy, inverse_of: :subscription
    has_and_belongs_to_many :orders, join_table: :spree_orders_subscriptions
    belongs_to :user
    belongs_to :credit_card
    alias_attribute :items, :subscription_items

    belongs_to :bill_address, foreign_key: :bill_address_id, class_name: 'Spree::SubscriptionAddress'
    alias_attribute :billing_address, :bill_address

    belongs_to :ship_address, foreign_key: :ship_address_id, class_name: 'Spree::SubscriptionAddress'
    alias_attribute :shipping_address, :ship_address

    has_many :subscription_skips, dependent: :destroy, inverse_of: :subscription
    alias_attribute :skips, :subscription_skips

    accepts_nested_attributes_for :ship_address
    accepts_nested_attributes_for :bill_address

    validates_presence_of :ship_address
    validates_presence_of :bill_address
    validates_presence_of :user

    after_save :reset_failure_count, if: :credit_card_id_changed?

    class << self
      def active
        where(state: 'active')
      end

      def paused
        where(state: 'paused')
      end

      def with_interval
        where('interval > 0')
      end

      def prepaid
        where(prepaid: true)
      end

      def good_standing
        where('failure_count < 6')
      end

      def ready_for_next_order
        subscriptions = active.with_interval.good_standing.select do |subscription|
          last_order = subscription.last_order
          next unless last_order
          next if subscription.prepaid?
          subscription.next_shipment_date.to_date <= Date.today
        end

        where(id: subscriptions.collect(&:id))
      end

      def ready_to_resume
        where(["state = ? and resume_at <= ?", :paused, Time.now])
      end
    end

    def products
      subscription_items.map(&:variant)
    end

    def last_shipment_date
      last_order.completed_at if last_order
    end

    def next_shipment_date
      if skip_order_at
        skip_order_at.advance(calc_next_renewal_date)
      elsif last_order
        last_order.completed_at.advance(calc_next_renewal_date)
      end
    end

    def calc_next_renewal_date
      { weeks: interval }
    end

    def active?
      self.state == 'active'
    end

    def cancelled?
      state == 'cancelled'
    end

    def paused?
      state == 'paused'
    end

    def cancel
      update_attribute(:state, 'cancelled')
      update_attribute(:cancelled_at, Time.now)
    end

    alias_method :cancel!, :cancel

    def last_order
      orders.complete.reorder("completed_at desc").first
    end

    def last_order_credit_card
      last_order.payments.where('amount > 0').where(state: 'completed').last.source
    end

    def last_order_date
      orders.first.complete? ? orders.first.completed_at : orders.first.created_at
    end

    def next_order
      next_order = NullObject.new

      next_order.class_eval do
        def created_at
          '???'
        end
      end

      next_order
    end

    def create_next_order!
      # just keeping safe
      non_existing_attributes = Spree::SubscriptionAddress.dup.attribute_names - Spree::Address.attribute_names

      # use subscription's addresses for the new order and email
      created_order = orders.create!(
        user: last_order.user,
        repeat_order: true,
        bill_address: Spree::Address.new(bill_address.dup.attributes.except(*non_existing_attributes)),
        ship_address: Spree::Address.new(ship_address.dup.attributes.except(*non_existing_attributes)),
        channel: 'subscription'
      )
      created_order.update_column(:email, email) if email
      created_order
    end

    def prepaid?
      false
    end

    def eligible_for_processing?
      active? && (!prepaid? || duration > 1)
    end

    def prepaid_balance_remaining?
      prepaid_amount > 0
    end

    def retry_count
      5 - failure_count
    end

    def increment_failure_count
      update_column(:failure_count, failure_count + 1)
    end

    def reset_failure_count
      update_column(:failure_count, 0)
    end

    def skip_next_order
      skips.create(skip_at: next_shipment_date) if can_skip?
    end

    def undo_skip_next_order
      last_skip.update_attribute(:undo_at, Time.now) if skipping?
    end

    def skip_order_at
      last_skip.skip_at if skipping?
    end

    def last_skip
      skips.last if skips.any? && skips.last.undo_at.nil? && skips.last.renewed_at.nil?
    end

    alias_attribute :skipping?, :last_skip

    def can_skip
      # only allow skipping after date has pass
      skipping? ? Date.today >= skip_order_at.to_date : true
    end

    def clear_skip_order
      last_skip.update_attribute(:renewed_at, Date.today) if skipping?
    end

    alias_attribute :can_skip?, :can_skip

    def pause
      update_attributes(pause_at: Time.now, resume_at: nil, state: 'paused')
    end

    def resume(resume_at_date = Time.now)
      update_attributes(resume_at: resume_at_date)
      update_attributes(pause_at: nil, state: 'active') if (resume_at_date.to_date <= Date.today)
    end

    def completed_orders
      orders.complete
    end

    # fetch the last completed order shipment
    def shipment
      last_order.shipments.last
    end

    # fetch the last completed order shipping method
    def shipping_method
      shipment.shipping_method
    end

    def failed_last_renewal?
      !orders.first.complete?
    end

    def can_renew?
      !(interval.nil? || interval.zero?) && !cancelled? && !paused?
    end

    def add_new_credit_card(params)
      ::Spree::CreditCard.transaction do
        credit_card = user.credit_cards.create(params)
        update_column(:credit_card_id, credit_card.id)

        CardStore.store_card_for_user(user, credit_card, credit_card.verification_value)
      end
    end

    def subscription_log_for(order)
      ::SubscriptionLog.where(order_id: order.id).last
    end

    def as_json(options = { })
      super((options || { }).merge({
          :methods => [:next_shipment_date, :skip_order_at]
      }))
    end

  end
end

app/controllers/spree/admin/subscriptions_controller.rb
module Spree
  module Admin
    class SubscriptionsController < ResourceController

      before_action :require_order_id, only: [:new]
      before_action :load_payment_methods, only: [:credit_card]

      def new
        order_id = params[:order_id]

        unless order_id.nil?
          order = Spree::Order.find(order_id)
          @subscription = build_subscription_from_order(order)

          # build subscription addresses
          user = order.user
          @subscription.build_ship_address(order.ship_address.dup.attributes.merge({user_id: user.id}))
          @subscription.build_bill_address(order.bill_address.dup.attributes.merge({user_id: user.id}))

          # build items
          build_subscription_items(@subscription, order)
        end
      end

      def create
        @subscription = Spree::Subscription.new(permitted_resource_params)
        build_subscription_items(@subscription, @subscription.orders.first)

        if @subscription.save
          flash[:success] = flash_message_for(@subscription, :subscription_created)

          redirect_to edit_object_url(@subscription)
        else
          flash[:error] = Spree.t(:subscription_could_not_be_created)

          render :new
        end
      end

      def renew
        before_failure_count = @object.failure_count
        ::GenerateSubscriptionOrder.new(@object).call

        # check if the failure count has increase, that means we have an error
        if  @object.failure_count > before_failure_count
          flash[:error] = flash_message_for(@object, :error_renew)
        else
          flash[:success] = flash_message_for(@object, :successfully_renewed)
        end
        respond_with(@object) do |format|
          format.html { redirect_to location_after_save }
        end
      end

      def cancel
        if @object.cancel
          flash[:success] = flash_message_for(@object, :successfully_cancelled)
          respond_with(@object) do |format|
            format.html { redirect_to collection_url }
          end
        end
      end

      def skip
        if @object.skip_next_order
          flash[:success] = flash_message_for(@object, :successfully_skipped)
          respond_with(@object) do |format|
            format.html { redirect_to location_after_save }
          end
        end
      end

      def undo_skip
        if @object.undo_skip_next_order
          flash[:success] = flash_message_for(@object, :successfully_undo_skip)
          respond_with(@object) do |format|
            format.html { redirect_to location_after_save }
          end
        end
      end

      # creates a new credit card and attaches it to the subscription
      def credit_card
        if request.post?
          begin
            # get the payment_method_id
            credit_card_params = object_params[:source_attributes].merge Hash[*object_params.first]
            @object.add_new_credit_card(credit_card_params)
          rescue Spree::Core::GatewayError, CardStore::CardError => e
            flash[:error] = "#{e.message}"
          end

          redirect_to credit_card_admin_subscription_url(@object)
        end
      end

      def failures
        @subscriptions = Spree::Subscription.active.where('failure_count > 0').order('created_at desc')
      end

      def adjust_sku
        old_sku = params[:old_sku]
        new_sku = params[:new_sku]
        if request.post?
          begin
            @subscriptions = AdjustSkuService.new.update_subscription(old_sku, new_sku)
          rescue => error
            flash[:error] = "SKU's could not be updated: #{error.message}"
          end
        end
      end

      protected
        def collection
          return @collection if defined?(@collection)
          params[:q] ||= HashWithIndifferentAccess.new
          params[:q][:s] ||= 'id desc'

          @collection = super
          @search = @collection.ransack(params[:q])
          @collection = @search.result(distinct: true).
            includes(subscription_includes).
            page(params[:page]).
            per(params[:per_page] || Spree::Config[:orders_per_page])

          @collection
        end

        def location_after_save
          edit_object_url(@object)
        end

      private
        def require_order_id
          if params[:order_id].blank?
            redirect_to admin_subscriptions_url
            flash[:error] = flash_message_for(@object, :requires_order_id)
          end
        end

        def build_subscription_from_order(order)
          attrs = {
            user_id: order.user.id,
            state: 'active',
            interval: order.subscription_interval,
            credit_card_id: order.credit_card_id_if_available
          }
          order.build_subscription(attrs)
        end

        def build_subscription_items(subscription, order)
          order.line_items.each do |line_item|
            subscription.subscription_items.build(
              subscription: subscription,
              variant: line_item.variant,
              quantity: line_item.quantity,
              price: line_item.price
            )
          end
        end

        def load_payment_methods
          @payment_methods = PaymentMethod.available(:back_end).select{ |method| method.type =~ /Gateway/ }
          @payment_method = @payment_methods.first
        end

        def object_params
          if params[:payment] and params[:payment_source] and source_params = params.delete(:payment_source)[params[:payment][:payment_method_id]]
            params[:payment][:source_attributes] = source_params
          end
          params.require(:payment).permit(permitted_payment_attributes)
        end

        def subscription_includes
          [:user, :orders, :subscription_items]
        end
    end
  end
end

app/controllers/spree/api/subscriptions_controller.rb
module Spree
  module Api
    class SubscriptionsController < Spree::Api::BaseController
      before_action :find_subscription, except: [:index]

      def self.prepended(base)
        base.prepend_after_action :deliver_cancellation_email, only: [:cancel]
        base.prepend_after_action :deliver_pause_email, only: [:pause]
        # need to touch user so the address list is updated
        base.prepend_after_action :touch_user, only: [:update_address, :create_address, :select_address]
      end

      def index
        render json: current_api_user.subscriptions,
          root: false,
          each_serializer: SubscriptionSerializer
      end

      def show
        render_subscription
      end

      def update
        @previous_interval = @subscription.interval
        result = @subscription.update_attributes(subscription_params)

        if result
          render json: @subscription.to_json
          Spree::SubscriptionMailer.delay.updated(@subscription, @previous_interval)
        else
          invalid_resource!(@subscription)
        end
      end

      def skip_next_order
        @subscription.skip_next_order

        render_subscription
      end

      def undo_skip_next_order
        @subscription.undo_skip_next_order

        render_subscription
      end

      def cancel
        @subscription.cancel

        render_subscription
      end

      def pause
        @subscription.pause

        render_subscription
      end

      def resume
        @subscription.resume

        render_subscription
      end

      def create_address
        new_address = Spree::SubscriptionAddress.create(address_params)

        if new_address.errors.empty?
          # attribute is either ship_address or bill_address
          @subscription.send("#{params[:attribute]}=", new_address)
          @subscription.save

          render json: @subscription.send(params[:attribute]).to_json
        else
          invalid_resource!(new_address)
        end
      end

      def update_address
        result = @subscription.send(params[:attribute]).dup.update_attributes(address_params)

        if result
          @subscription.touch

          render json: @subscription.send(params[:attribute]).to_json
        else
          invalid_resource!(@subscription.send(params[:attribute]))
        end
      end

      def select_address
        @subscription.send("#{params[:attribute]}=", find_subscription_address)
        if @subscription.save
          render json: @subscription.send(params[:attribute]).to_json
        else
          invalid_resource!(@subscription.send(params[:attribute]))
        end
      end

      # create a new credit card
      # then assign it to the subscription
      def create_credit_card
        order = @subscription.last_order
        credit_card = nil
        begin
          ::Spree::CreditCard.transaction do
            credit_card = current_api_user.credit_cards.build(credit_card_params)
            credit_card.save

            @subscription.credit_card = credit_card
            @subscription.save

            CardStore.store_card_for_user(current_api_user, credit_card, credit_card.verification_value)
          end

          render_subscription
        rescue CardStore::CardError
          @resource = credit_card
          render "sprangular/errors/invalid", status: 422
        end
      end

      private

      def deliver_cancellation_email
        Spree::SubscriptionMailer.cancel(@subscription).deliver_later
      end

      def deliver_pause_email
        Spree::SubscriptionMailer.pause(@subscription).deliver_later
      end

      def touch_user
        @subscription.user.touch
      end

      def render_subscription
        render json: @subscription,
          root: false,
          serializer: SubscriptionSerializer
      end

      def find_subscription
        @subscription ||= Spree::Subscription.accessible_by(current_ability, :read).find(params[:id])
      end

      def find_subscription_address
        @subscription_address ||= Spree::SubscriptionAddress.accessible_by(current_ability, :read).find(params[:address_id])
      end

      def address_params
        params.require(:address).permit(permitted_address_params)
      end

      def subscription_params
        params.require(:subscription).permit(permitted_subscription_attributes)
      end

      def credit_card_params
        params.require(:credit_card).permit!
      end

      def permitted_address_params
        [:firstname, :lastname, :address1, :address2, :city, :phone, :zipcode, :state_id, :state_name, :country_id, :user_id]
      end

      def permitted_subscription_attributes
        [:interval, :credit_card_id, :email]
      end
    end
  end
end

app/views/spree/admin/subscriptions/_sidebar.html.erb
<% content_for :sidebar_title do %>
  <%= Spree.t(:addl_information) %>
<% end %>

<% content_for :sidebar do %>
  <header id="subscription_tab_summary" data-hook>
  <dl class="additional-info">
    <dt>Id:</dt>
    <dd><%= @subscription.id %></dd>
    <dt>Status</dt>
    <dd><span class="state <%= @subscription.active? ? 'success' : 'canceled' %>"><%= Spree.t(@subscription.state, :scope => :subscription_state) %></span></dd>
    <% if @subscription.cancelled? %>
      <dt>Cancelled at</dt>
      <dd><%= l(@subscription.cancelled_at, format: :long) %></dd>
    <% end %>
    <% if @subscription.can_renew? %>
      <dt>Renewal date</dt>
      <dd>
        <%= l(@subscription.next_shipment_date, format: :subscription_date_format) %>
        (<%= link_to 'Renew Now', renew_admin_subscription_path(@subscription), method: :put, data: { confirm: 'Are you sure you want to renew the subscription?' } %>)
      </dd>
      <dt>Skip order</dt>
      <dd><%= @subscription.skip_order_at ? 'Yes' : 'No' %></dd>
      <dt>Skip order at</dt>
      <dd>
        <%= l(@subscription.skip_order_at, format: :subscription_date_format) if @subscription.skipping? %>
        <%= link_to 'Skip', skip_admin_subscription_path(@subscription), method: :put if @subscription.can_skip? %>
        <%= link_to 'Undo', undo_skip_admin_subscription_path(@subscription), method: :put if @subscription.skipping? %>
      </dd>
      <dt>Failed renewals</dt>
      <dd><%= @subscription.failure_count %></dd>
    <% end %>
    <% if @subscription.paused? %>
      <dt>Paused at</dt>
      <dd><%= l(@subscription.pause_at, format: :subscription_date_format) %></dd>
    <% end %>
    <% if @subscription.resume_at %>
      <dt>Resumed at</dt>
      <dd><%= l(@subscription.resume_at, format: :subscription_date_format) %></dd>
    <% end %>
    <dt>Completed orders</dt>
    <dd><%= @subscription.orders.complete.count %></dd>
    <dt>User</dt>
    <dd><%= link_to(@subscription.user.email, edit_admin_user_path(@subscription.user), target: '_blank') %></dd>
    <dt>Shipping Method</dt>
    <dd><%= @subscription.shipping_method.name if @subscription.shipment && @subscription.shipping_method %></dd>
    <dt>Credit card </dt>
    <% if @subscription.credit_card %>
      <dd><%= link_to @subscription.credit_card.display_number, credit_card_admin_subscription_path(@subscription) %></dd>
    <% else %>
      <dd><%= link_to Spree.t(:create), credit_card_admin_subscription_path(@subscription) %></dd>
    <% end %>
    <dt>Last updated</dt>
    <dd><%= l(@subscription.updated_at, format: :long) %></dd>
  </dt>
  </header>
<% end %>

app/views/spree/admin/subscriptions/credit_card.html.erb
<% content_for :page_title do %>
  <%= t(:credit_card) %>
<% end %>

<% content_for :page_actions do %>
  <li><%= button_link_to Spree.t(:back_to_subscription), edit_admin_subscription_url(@object), :icon => 'arrow-left' %></li>
<% end %>

<%= render partial: 'spree/admin/subscriptions/sidebar' %>

<div class="alpha nine columns new_payment" id="new_payment">
  <div class="field">
    <% if @object.credit_card %>    
    <label><%= Spree.t(:current) %></label>
    <fieldset class="no-border-bottom">
      <dl>
        <dt>ID</dt><dd><%= @object.credit_card.id %></dd>
        <dt>Name</dt><dd><%= @object.credit_card.name %> </dd>
        <dt>Number</dt><dd><%= @object.credit_card.display_number %></dd>
        <dt>Expiration</dt><dd><%= @object.credit_card.month %>/<%= @object.credit_card.year %></dd>
        <dt>Type</dt><dd><%= @object.credit_card.cc_type %></dd>
        <dt>Gateway customer id</dt><dd> <%= @object.credit_card.gateway_customer_profile_id %></dd>
        <dt>Gateway credit card id</dt><dd> <%= @object.credit_card.gateway_payment_profile_id %></dd>
        <dt>Provider</dt><dd><%= @object.credit_card.payment_method.type %></dd>
      </dl>
    </fieldset>
    <% end %>
    <%= form_tag credit_card_admin_subscription_path(@object) do |f| %>
      <label><%= Spree.t(:new_payment_method) %></label>
      <ul>
        <% @payment_methods.each do |method| %>
          <li data-id="<%= Spree.t(method.name, :scope => :payment_methods, :default => method.name).parameterize %>">
            <label data-hook="payment_method_field">
              <%= radio_button_tag 'payment[payment_method_id]', method.id, method == @payment_method, { class: "payment_methods_radios" } %>
              <%= Spree.t(method.name, :scope => :payment_methods, :default => method.name) %>
            </label>
          </li>
        <% end %>
      </ul>

      <div class="payment-method-settings">
        <% @payment_methods.each do |method| %>
          <div class="payment-methods" id="payment_method_<%= method.id %>">
            <% if method.source_required? %>
              <%= render :partial => "spree/admin/payments/source_forms/gateway", :locals => { :payment_method => method, :previous_cards => [] } %>
            <% end %>
          </div>
        <% end %>
      </div>
      
      <fieldset class="no-border-top">
        <div class="filter-actions actions" data-hook="buttons">
          <%= button Spree.t('actions.add'), 'plus' %>
        </div>
      </fieldset>
    <% end %>
  </div>
</div>

app/views/spree/admin/subscriptions/failures.html.erb
<h2> Showing subscriptions that failed renewing</h2>
<b> Total: <%= @subscriptions.count %>
<br/>
<br/>
<table id="listing_subscriptions" class="index responsive">
  <thead>
    <tr>
      <th>id</th>
      <th>date</th>
      <th>order</th>
      <th>email</th>
      <th>renewal date</th>
      <th>attempts</th>
    </tr>
  </thead>
  <tbody>
    <% @subscriptions.each do |subscription| %>
      <tr>
        <td><%= link_to subscription.id, edit_admin_subscription_path(subscription), target: '_blank' %>
        <td><%= l(subscription.last_order_date, format: :subscription_date_format) %>
        <td><%= link_to subscription.orders.first.number, edit_admin_order_path(subscription.orders.first), target: '_blank' %>
        <td><%=link_to subscription.user.email, edit_admin_user_path(subscription.user), target: '_blank' %>
        <td><%= l(subscription.next_shipment_date, format: :subscription_date_format) %>
        <td><%= subscription.failure_count %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/spree/admin/subscriptions/index.html.erb
<% content_for :page_title do %>
  <%= t(:listing_subscriptions) %>
<% end %>

<% content_for :page_actions do %>
  <li></li>
<% end %>

<% content_for :table_filter_title do %>
  <%= Spree.t(:search) %>
<% end %>

<% content_for :table_filter do %>
  <div data-hook="admin_subscriptions_index_search">
    <%= search_form_for [:admin, @search] do |f| %>
      <div class="four columns alpha">
        <div class="date-range-filter field">
          <%= label_tag :q_created_at_gt, Spree.t(:date_range) %>
          <div class="date-range-fields">
            <%= f.text_field :created_at_gt, :class => 'datepicker datepicker-from', :value => params[:q][:created_at_gt], :placeholder => Spree.t(:start) %>

            <span class="range-divider">
              <i class="fa fa-arrow-right"></i>
            </span>

            <%= f.text_field :created_at_lt, :class => 'datepicker datepicker-to', :value => params[:q][:created_at_lt], :placeholder => Spree.t(:stop) %>
          </div>
        </div>
      </div>

      <div class="four columns">
        <div class="field">
          <%= label_tag :q_user_email_cont, Spree.t(:email) %>
          <%= f.text_field :user_email_cont, tabindex: 2 %>
        </div>
      </div>

      <div class="four columns">
        <div class="field">
          <%= label_tag :q_orders_number_cont, Spree.t(:order_number) %>
          <%= f.text_field :orders_number_cont, tabindex: 3 %>
        </div>
      </div>

      <div class="four columns omega">
        <div class="field">
          <%= label_tag :q_id_eq, Spree.t(:id) %>
          <%= f.text_field :id_eq, tabindex: 1 %>
        </div>
      </div>

      <div class="four columns omega">
        <div class="field">
          <%= label_tag :q_old_sku, Spree.t(:sku) %>
          <%= f.text_field :subscription_items_variant_sku_eq, tabindex: 3 %>
        </div>
      </div>

      <div class="clearfix"></div>

      <div class="actions filter-actions">
        <div data-hook="admin_promotions_index_search_buttons">
          <%= button Spree.t(:filter_results), 'search' %>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

<% unless @subscriptions.empty? %>
  <div class="pagination">
    <%= page_entries_info @collection %>
  </div>
  <table class="index responsive" id="listing_subscriptions" data-hook width="100%">
    <colgroup>
       <col style="width: 5%;">
       <col style="width: 8%;">
       <col style="width: 10%;">
       <col style="width: 18%;">
       <col style="width: 15%;">
       <col style="width: 3%;">
       <col style="width: 9%;">
       <col style="width: 9%;">
    </colgroup>
    <thead>
      <tr data-hook="admin_subscriptions_index_headers">
        <th>ID</th>
        <th>State</th>
        <th>Frequency</th>
        <th>Last Order</th>
        <th>User</th>
        <th>Skip</th>
        <th>Renew Date</th>
        <th data-hook="admin_subscriptions_index_header_actions" class="actions"></th>
      </tr>
    </thead>
    <tbody>
    <% @subscriptions.each do |subscription| %>
      <tr data-hook="admin_subscriptions_index_rows" class="<%= cycle('odd', 'even') %>">
        <td class="align-center"><%= subscription.id %></td>
        <td class="align-center">
            <span class="state <%= subscription.active? ? 'success' : 'canceled' %>"><%= subscription.state %></span>
        </td>
        <td class="align-center">
          <% if subscription.can_renew? %>
          Every  <%= pluralize(subscription.interval, 'month') %>
          <% end %>
        </td>
        <td>
          <span class="state <%= subscription.orders.first.state.downcase %>">
            <%= link_to subscription.orders.first.number, edit_admin_order_path(subscription.last_order), target: '_blank' %>
          </span>
          <br />
          <%= l(subscription.last_order_date, format: :long)  %>
          <br />
          <%= subscription.shipping_method.name if subscription.shipment && subscription.shipment.shipping_method %>
        </td>
        <td class="align-center">
          <%= link_to(subscription.user.email, edit_admin_user_path(subscription.user), target: '_blank') if subscription.user %>
        </td>
        <td class="align-center"><%= subscription.skip_order_at ? 'Yes' : '' if subscription.can_renew? %></td>
        <td class="align-center"><%= l(subscription.next_shipment_date, format: :subscription_date_format) if subscription.can_renew? %></td>
        <td class='actions align-center' data-hook="admin_subscriptions_index_row_actions">
          <%=
            link_to_with_icon 'edit', 'Edit', edit_admin_subscription_path(subscription), no_text: true
          -%>
          <%=
            unless subscription.cancelled?
              link_to_with_icon 'cancel', 'Cancel', cancel_admin_subscription_path(subscription),
                no_text: true, method: :put, data: { confirm: t(:are_you_sure), action: 'remove' }
            end
          -%>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
<% else %>
  <div class="no-objects-found">
    <%= t(:no_subscriptions_found)%>
  </div>
<% end %>

<%= paginate @subscriptions %>

app/views/spree/admin/subscriptions/new.html.erb
<% content_for :page_title do %>
  <%= t(:new_subscription) %>
<% end %>

<%= form_for @subscription, :url => admin_subscriptions_path(@subscription) do |f| %>
  <%= f.hidden_field :order_ids, value: params[:order_id] %>

  <%= f.hidden_field :state %>
  <%= f.hidden_field :user_id %>
  <%= f.hidden_field :duration %>
  <%= f.hidden_field :prepaid_amount %>
  <%= f.hidden_field :credit_card_id %>

  <fieldset class="index no-border-bottom">
    <legend align="center"><%= Spree.t("admin.subscription") %></legend>
    <%= render :partial => 'form', :locals => { :f => f } %>
  </fieldset>

  <%= render partial: 'spree/admin/subscriptions/addresses', :locals => { :f => f } %>

  <%= render partial: 'spree/admin/subscriptions/items' %>

  <div class="clear"></div>
  <fieldset class="index no-border-top">
    <div class="form-buttons filter-actions actions" data-hook="buttons">
      <%= button Spree.t('actions.create'), 'create' %>
    </div>
  </fieldset>

<% end %>