config/routes.rb
Spree::Core::Engine.add_routes do
  namespace :admin do
    resources :subscriptions, except: [:show, :destroy] do
      member do
        put :cancel
        put :renew
        put :skip
        put :undo_skip
        get :credit_card
        post :credit_card
      end
      collection do
        get :failures
        get :adjust_sku
        post :adjust_sku
      end
    end
  end

  namespace :api, defaults: { format: 'json' } do
    resources :subscriptions, except: [:create, :new, :destroy] do
      member do
        put :skip_next_order
        put :undo_skip_next_order
        put :pause
        put :resume
        post :create_address
        put :update_address
        put :select_address
        put :cancel
        post :create_credit_card
      end
      resources :subscription_items
    end
  end

  resources :subscriptions do
    member do
        put :pause
        put :resume
        put :cancel
        post :add_item
        get :credit_card
        post :credit_card
    end
    resources :subscription_items
  end
end

app/models/spree/ability_decorator.rb
module Spree
  class AbilityDecorator
    include CanCan::Ability

    def initialize(user)
      can :read, Spree::Subscription, user_id: user.id
      can :read, Spree::SubscriptionItem, subscription: { user_id: user.id}
      can :read, Spree::SubscriptionAddress, user_id: user.id
    end
  end
end

Spree::Ability.register_ability(Spree::AbilityDecorator)

app/models/spree/credit_card_decorator.rb
module Spree
  module CreditCardExtensions
    def payment_provider
      gateway_customer_profile_id.include?('cus_') ? 'Stripe' : 'Unknown'
    rescue
      'Unknown'
    end
  end
end

::Spree::CreditCard.prepend ::Spree::CreditCardExtensions

app/models/spree/product_decorator.rb
module Spree
  module ProductExtensions

    def self.prepended(base)
      class << base
        prepend ClassMethods
      end
    end

    module ClassMethods
      def subscribable
        where(subscribable: true)
      end
    end
  end
end

::Spree::Product.prepend Spree::ProductExtensions

app/models/spree/subscription_address.rb
module Spree
  class SubscriptionAddress < Spree::Address
    self.table_name = 'spree_subscription_addresses'  

    belongs_to :user
  end
end

app/models/spree/subscription_skip.rb
module Spree
  class SubscriptionSkip < ActiveRecord::Base
    belongs_to :subscription, class_name: "Spree::Subscription", touch: true
  end
end

app/models/spree/variant_decorator.rb
module Spree
  module VariantExtensions

    delegate :subscribable?, to: :product
    
  end
end

::Spree::Variant.prepend Spree::VariantExtensions

app/controllers/spree/admin/subscriptions_controller.rb
module Spree
  module Admin
    class SubscriptionsController < ResourceController

      before_action :require_order_id, only: [:new]
      before_action :load_payment_methods, only: [:credit_card]

      def new
        order_id = params[:order_id]

        unless order_id.nil?
          order = Spree::Order.find(order_id)
          @subscription = build_subscription_from_order(order)

          # build subscription addresses
          user = order.user
          @subscription.build_ship_address(order.ship_address.dup.attributes.merge({user_id: user.id}))
          @subscription.build_bill_address(order.bill_address.dup.attributes.merge({user_id: user.id}))

          # build items
          build_subscription_items(@subscription, order)
        end
      end

      def create
        @subscription = Spree::Subscription.new(permitted_resource_params)
        build_subscription_items(@subscription, @subscription.orders.first)

        if @subscription.save
          flash[:success] = flash_message_for(@subscription, :subscription_created)

          redirect_to edit_object_url(@subscription)
        else
          flash[:error] = Spree.t(:subscription_could_not_be_created)

          render :new
        end
      end

      def renew
        before_failure_count = @object.failure_count
        ::GenerateSubscriptionOrder.new(@object).call

        # check if the failure count has increase, that means we have an error
        if  @object.failure_count > before_failure_count
          flash[:error] = flash_message_for(@object, :error_renew)
        else
          flash[:success] = flash_message_for(@object, :successfully_renewed)
        end
        respond_with(@object) do |format|
          format.html { redirect_to location_after_save }
        end
      end

      def cancel
        if @object.cancel
          flash[:success] = flash_message_for(@object, :successfully_cancelled)
          respond_with(@object) do |format|
            format.html { redirect_to collection_url }
          end
        end
      end

      def skip
        if @object.skip_next_order
          flash[:success] = flash_message_for(@object, :successfully_skipped)
          respond_with(@object) do |format|
            format.html { redirect_to location_after_save }
          end
        end
      end

      def undo_skip
        if @object.undo_skip_next_order
          flash[:success] = flash_message_for(@object, :successfully_undo_skip)
          respond_with(@object) do |format|
            format.html { redirect_to location_after_save }
          end
        end
      end

      # creates a new credit card and attaches it to the subscription
      def credit_card
        if request.post?
          begin
            # get the payment_method_id
            credit_card_params = object_params[:source_attributes].merge Hash[*object_params.first]
            @object.add_new_credit_card(credit_card_params)
          rescue Spree::Core::GatewayError, CardStore::CardError => e
            flash[:error] = "#{e.message}"
          end

          redirect_to credit_card_admin_subscription_url(@object)
        end
      end

      def failures
        @subscriptions = Spree::Subscription.active.where('failure_count > 0').order('created_at desc')
      end

      def adjust_sku
        old_sku = params[:old_sku]
        new_sku = params[:new_sku]
        if request.post?
          begin
            @subscriptions = AdjustSkuService.new.update_subscription(old_sku, new_sku)
          rescue => error
            flash[:error] = "SKU's could not be updated: #{error.message}"
          end
        end
      end

      protected
        def collection
          return @collection if defined?(@collection)
          params[:q] ||= HashWithIndifferentAccess.new
          params[:q][:s] ||= 'id desc'

          @collection = super
          @search = @collection.ransack(params[:q])
          @collection = @search.result(distinct: true).
            includes(subscription_includes).
            page(params[:page]).
            per(params[:per_page] || Spree::Config[:orders_per_page])

          @collection
        end

        def location_after_save
          edit_object_url(@object)
        end

      private
        def require_order_id
          if params[:order_id].blank?
            redirect_to admin_subscriptions_url
            flash[:error] = flash_message_for(@object, :requires_order_id)
          end
        end

        def build_subscription_from_order(order)
          attrs = {
            user_id: order.user.id,
            state: 'active',
            interval: order.subscription_interval,
            credit_card_id: order.credit_card_id_if_available
          }
          order.build_subscription(attrs)
        end

        def build_subscription_items(subscription, order)
          order.line_items.each do |line_item|
            subscription.subscription_items.build(
              subscription: subscription,
              variant: line_item.variant,
              quantity: line_item.quantity,
              price: line_item.price
            )
          end
        end

        def load_payment_methods
          @payment_methods = PaymentMethod.available(:back_end).select{ |method| method.type =~ /Gateway/ }
          @payment_method = @payment_methods.first
        end

        def object_params
          if params[:payment] and params[:payment_source] and source_params = params.delete(:payment_source)[params[:payment][:payment_method_id]]
            params[:payment][:source_attributes] = source_params
          end
          params.require(:payment).permit(permitted_payment_attributes)
        end

        def subscription_includes
          [:user, :orders, :subscription_items]
        end
    end
  end
end

app/controllers/spree/api/subscription_items_controller.rb
module Spree
  module Api
    class SubscriptionItemsController < Spree::Api::BaseController
      before_action :find_subscription, only: [:create, :destroy]
      before_action :find_subscription_item, only: [:update, :destroy]

      def create
        variant = Spree::Variant.find(params[:subscription_item][:variant_id])
        @subscription_item = @subscription.subscription_items.create(
            variant: variant,
            quantity: params[:subscription_item][:quantity] || 1
        )

        if @subscription_item.errors.empty?
          render json: @subscription_item.to_json
        else
          invalid_resource!(@subscription_item)
        end
      end


      def update
        result = @subscription_item.update_attributes(subscription_items_params)

        if result
          render json: @subscription_item.to_json
        else
          invalid_resource!(@subscription_item)
        end
      end

      def destroy
        @subscription.subscription_items.destroy(params[:id])

        respond_with(@subscription_item, status: 204)
      end

      private
      def find_subscription
        @subscription ||= Spree::Subscription.accessible_by(current_ability, :read).find(params[:subscription_id])
      end


      def find_subscription_item
        @subscription_item ||= Spree::SubscriptionItem.accessible_by(current_ability, :read).find(params[:id])
      end

      def subscription_items_params
        params.require(:subscription_item).permit(permitted_subscription_item_attributes)
      end

      def permitted_subscription_item_attributes
        [
          :quantity, :variant_id
        ]
      end
    end
  end
end

app/controllers/spree/api/subscriptions_controller.rb
module Spree
  module Api
    class SubscriptionsController < Spree::Api::BaseController
      before_action :find_subscription, except: [:index]

      def self.prepended(base)
        base.prepend_after_action :deliver_cancellation_email, only: [:cancel]
        base.prepend_after_action :deliver_pause_email, only: [:pause]
        # need to touch user so the address list is updated
        base.prepend_after_action :touch_user, only: [:update_address, :create_address, :select_address]
      end

      def index
        render json: current_api_user.subscriptions,
          root: false,
          each_serializer: SubscriptionSerializer
      end

      def show
        render_subscription
      end

      def update
        @previous_interval = @subscription.interval
        result = @subscription.update_attributes(subscription_params)

        if result
          render json: @subscription.to_json
          Spree::SubscriptionMailer.delay.updated(@subscription, @previous_interval)
        else
          invalid_resource!(@subscription)
        end
      end

      def skip_next_order
        @subscription.skip_next_order

        render_subscription
      end

      def undo_skip_next_order
        @subscription.undo_skip_next_order

        render_subscription
      end

      def cancel
        @subscription.cancel

        render_subscription
      end

      def pause
        @subscription.pause

        render_subscription
      end

      def resume
        @subscription.resume

        render_subscription
      end

      def create_address
        new_address = Spree::SubscriptionAddress.create(address_params)

        if new_address.errors.empty?
          # attribute is either ship_address or bill_address
          @subscription.send("#{params[:attribute]}=", new_address)
          @subscription.save

          render json: @subscription.send(params[:attribute]).to_json
        else
          invalid_resource!(new_address)
        end
      end

      def update_address
        result = @subscription.send(params[:attribute]).dup.update_attributes(address_params)

        if result
          @subscription.touch

          render json: @subscription.send(params[:attribute]).to_json
        else
          invalid_resource!(@subscription.send(params[:attribute]))
        end
      end

      def select_address
        @subscription.send("#{params[:attribute]}=", find_subscription_address)
        if @subscription.save
          render json: @subscription.send(params[:attribute]).to_json
        else
          invalid_resource!(@subscription.send(params[:attribute]))
        end
      end

      # create a new credit card
      # then assign it to the subscription
      def create_credit_card
        order = @subscription.last_order
        credit_card = nil
        begin
          ::Spree::CreditCard.transaction do
            credit_card = current_api_user.credit_cards.build(credit_card_params)
            credit_card.save

            @subscription.credit_card = credit_card
            @subscription.save

            CardStore.store_card_for_user(current_api_user, credit_card, credit_card.verification_value)
          end

          render_subscription
        rescue CardStore::CardError
          @resource = credit_card
          render "sprangular/errors/invalid", status: 422
        end
      end

      private

      def deliver_cancellation_email
        Spree::SubscriptionMailer.cancel(@subscription).deliver_later
      end

      def deliver_pause_email
        Spree::SubscriptionMailer.pause(@subscription).deliver_later
      end

      def touch_user
        @subscription.user.touch
      end

      def render_subscription
        render json: @subscription,
          root: false,
          serializer: SubscriptionSerializer
      end

      def find_subscription
        @subscription ||= Spree::Subscription.accessible_by(current_ability, :read).find(params[:id])
      end

      def find_subscription_address
        @subscription_address ||= Spree::SubscriptionAddress.accessible_by(current_ability, :read).find(params[:address_id])
      end

      def address_params
        params.require(:address).permit(permitted_address_params)
      end

      def subscription_params
        params.require(:subscription).permit(permitted_subscription_attributes)
      end

      def credit_card_params
        params.require(:credit_card).permit!
      end

      def permitted_address_params
        [:firstname, :lastname, :address1, :address2, :city, :phone, :zipcode, :state_id, :state_name, :country_id, :user_id]
      end

      def permitted_subscription_attributes
        [:interval, :credit_card_id, :email]
      end
    end
  end
end

app/controllers/spree/subscription_items_controller.rb
module Spree
  class SubscriptionItemsController < Spree::StoreController
    before_action :find_subscription

    def destroy
      @subscription.subscription_items.destroy(params[:id])
      redirect_to :back
    end

    private

    def find_subscription
      @subscription = Spree::Subscription.accessible_by(current_ability, :read).find(params[:id])
    end
  end
end

app/controllers/spree/subscriptions_controller.rb
module Spree
  class SubscriptionsController < Spree::StoreController
    before_action :find_subscription, except: [:index]
    before_action :load_payment_methods, only: [:credit_card]

    def index
      @subscriptions = Spree::Subscription.accessible_by(current_ability, :read)
    end

    def pause
      @subscription.pause
      redirect_to :back
    end

    def resume
      @subscription.resume(resume_at_param)
      redirect_to :back
    end

    def cancel
      @subscription.cancel
      redirect_to :back
    end

    def update
      @subscription.attributes = resource_params
      render :edit
    end

    def add_item
      variant = Spree::Variant.accessible_by(current_ability, :read).find(params[:variant_id])

      return unless variant.product.subscribable?
      ::Spree::SubscriptionItem.create!(
        subscription: @subscription,
        variant: variant,
        quantity: 1,
        interval: @subscription.interval
      )
      render :edit
    end

    def credit_card
      if request.post?
        params = credit_card_params[:source_attributes].merge Hash[*credit_card_params.first]
        @subscription.add_new_credit_card(params)
      end
    end

    private

    def find_subscription
      @subscription = Spree::Subscription.accessible_by(current_ability, :read).find(params[:id])
    end

    def load_payment_methods
      @payment_methods = PaymentMethod.available(:back_end).select{ |method| method.type =~ /Gateway/ }
      @payment_method = @payment_methods.first
    end

    private

    def resource_params
      params.require(:subscription).permit!
    end

    def resume_at_param
      Date.parse(params.require(:subscription).require(:resume_at))
    end

    def credit_card_params
      if params[:payment] and params[:payment_source] and source_params = params.delete(:payment_source)[params[:payment][:payment_method_id]]
        params[:payment][:source_attributes] = source_params
      end
      params.require(:payment).permit(permitted_payment_attributes)
    end
  end
end

app/views/spree/subscriptions/_items.html.erb
<div id="line-items">

  <div id="add-line-item">
    <%= form_for @subscription, url: add_item_subscription_path(@subscription), method: :post do |form| %>
      <%= label_tag :line_item, Spree.t(:name_or_sku) %><br />
      <%= text_field_tag :variant_id %>
      <%= submit_tag t("action.add"), class: "add-line-item" %>
    <% end %>
  </div>

  <table
    <thead>
      <th><%= Spree.t(:name) %></th>
      <th><%= Spree.t(:price) %></th>
      <th><%= Spree.t(:quantity) %></th>
      <th><%= Spree.t(:total_price) %></th>
      <th>&nbsp;</th>
    </thead>

    <tbody>
      <% @subscription.subscription_items.each do |item| %>
        <tr>
          <td>
            <%= item.variant.product.name %><br>
            <%= "(" + variant_options(item.variant) + ")" unless item.variant.option_values.empty? %><br>
            <%= item.variant.sku %>
          </td>
          <td><%= number_to_currency(item.variant.price) %></td>
          <td><%= item.quantity %></td>
          <td><%= line_item_shipment_price(item, item.quantity) %></td>
          <td>
            <%= button_to t('action.delete'), [@subscription, item], method: :delete, class: "delete-subscription-item" %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

</div>

app/views/spree/subscriptions/credit_card.html.erb
<div id="payment-info">
  <% credit_card = @subscription.credit_card %>
  <dl id="current-payment-info">
    <dt>ID</dt><dd><%= credit_card.id %></dd>
    <dt>Name</dt><dd><%= credit_card.name %> </dd>
    <dt>Number</dt><dd><%= credit_card.display_number %></dd>
    <dt>Expiration</dt><dd><%= credit_card.month %>/<%= credit_card.year %></dd>
    <dt>Type</dt><dd><%= credit_card.cc_type %></dd>
    <dt>Gateway customer id</dt><dd> <%= credit_card.gateway_customer_profile_id %></dd>
    <dt>Gateway credit card id</dt><dd> <%= credit_card.gateway_payment_profile_id %></dd>
    <dt>Provider</dt><dd><%= credit_card.payment_method.type %></dd>
  </dl>

  <%= form_tag credit_card_subscription_path(@subscription) do |form| %>
    <label><%= Spree.t(:new_payment_method) %></label>
    <ul>
      <% @payment_methods.each do |method| %>
        <li>
          <label>
            <%= radio_button_tag 'payment[payment_method_id]', method.id, method == @payment_method %>
            <%= Spree.t(method.name, scope: :payment_methods, default: method.name) %>
          </label>
        </li>
      <% end %>
    </ul>

    <% @payment_methods.each do |method| %>
      <div class="card_form">
        <% if method.source_required? %>
          <% param_prefix = "payment_source[#{method.id}]" %>
          <%= hidden_field_tag "#{param_prefix}[cc_type]" %>

          <div class="form-group">
            <%= label_tag "card_number#{method.id}", raw(Spree.t(:card_number)) %><span class="required">*</span><br />
            <%= text_field_tag "#{param_prefix}[number]", '',  id: "card_number#{method.id}",  maxlength: 19, class: "card_number" %>
          </div>

          <div class="form-group">
            <%= label_tag "card_name#{method.id}", raw(Spree.t(:name)) %><span class="required">*</span><br />
            <%= text_field_tag "#{param_prefix}[name]", '', id: "card_name#{method.id}", maxlength: 19, class: "card_name" %>
          </div>

          <div class="form-group">
            <%= label_tag "card_expiry#{method.id}", raw(Spree.t(:expiration)) %><span class="required">*</span><br />
            <%= text_field_tag "#{param_prefix}[expiry]", '', id: "card_expiry#{method.id}", placeholder: "MM / YY", class: "card_expiry" %>
          </div>

          <div class="form-group">
            <%= label_tag "card_code#{method.id}", raw(Spree.t(:card_code)) %><span class="required">*</span><br />
            <%= text_field_tag "#{param_prefix}[verification_value]", '', id: "card_code#{method.id}", size: 5, class: "card_code" %>
            <a href="/content/cvv" class="info cvvLink" target="_blank">
              (<%= Spree.t(:what_is_this) %>)
            </a>
          </div>
        <% end %>
      </div>
    <% end %>

    <%= submit_tag t("action.add") %>
  <% end %>

</div>

app/views/spree/subscriptions/edit.html.erb
<% content_for :page_title do %>
  <%= t(:editing_subscription) %>
<% end %>

<%= form_for @subscription, url: subscription_path(@subscription) do |form| %>

  <fieldset class="index no-border-bottom">
    <legend align="center"><%= Spree.t("admin.subscription") %></legend>
    <%= render partial: 'spree/shared/form', locals: { f: form } %>
    <%= render partial: 'spree/shared/payment_info' %>
  </fieldset>

  <div class="row">
  <div class="col-sm-6" data-hook="billing_fieldset_wrapper">
  <div class="panel panel-default" id="billing" data-hook>
    <%= form.fields_for :bill_address do |bill_form| %>
      <div class="panel-heading">
        <h3 class="panel-title"><%= Spree.t(:billing_address) %></h3>
      </div>
      <div class="panel-body">
        <%= render partial: 'spree/address/form', locals: { form: bill_form, address_type: 'billing', address: @subscription.bill_address } %>
      </div>
    <% end %>
  </div>
  </div>

  <div class="col-sm-6" data-hook="shipping_fieldset_wrapper">
  <div class="panel panel-default" id="shipping" data-hook>
    <%= form.fields_for :ship_address do |ship_form| %>
      <div class="panel-heading">
        <h3 class="panel-title"><%= Spree.t(:shipping_address) %></h3>
      </div>
      <div class="panel-body">

        <%= render partial: 'spree/address/form', locals: { form: ship_form, address_type: 'shipping', address: @subscription.ship_address } %>
      </div>
    <% end %>
  </div>
  </div>
  </div>

  <div class="well text-right form-buttons" data-hook="buttons">
  <%= submit_tag Spree.t(:save_and_continue), class: 'btn btn-lg btn-success' %>
  </div>

<% end %>

<%= render partial: 'items' %>

app/views/spree/subscriptions/index.html.erb
<%= render partial: 'spree/users/subscriptions', locals: { subscriptions: @subscriptions } %>